services:
  - type: web
    name: ai-code-reviewer-backend
    env: python
    runtime: python-3.13.0
    buildCommand: cd backend && pip install -r requirements.txt
    startCommand: cd backend && uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: DB_USERNAME
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: DB_CLUSTER_URL
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: JWT_ALGORITHM
        value: HS256
      - key: GEMINI_API_KEY
        sync: false
